#Añade aqui tus rangos, puedes modificar borrar o añadir mas rangos.
warpLimits:
  default: 5
#  Diamante: 10
#  vip: 20
#  OWNER: 50

messages:
  setpwarpUsage: "§cUso incorrecto del comando. Usa /setpwarp <nombre>."
  maxWarpsExceeded: "§cHas alcanzado el límite máximo de warps. No puedes añadir más."
  warpSaved: "§aWarp guardado con éxito."
  onlyPlayers: "§cEste comando solo puede ser ejecutado por jugadores."
  noWarps: "§cNo tienes warps guardados."
  warpsList: "§aLista de tus warps:"
  currentWarpCount: "§7Tienes %count% de %limit% warps."
  warpNotFound: "§cWarp no encontrado."
  teleportSuccess: "§aTe has teletransportado a %warpName%."
  delpwarpUsage: "§cUso incorrecto del comando. Usa /delpwarp <nombre>."
  warpDeleted: "§aWarp %warpName% eliminado con éxito."
  configReloaded: "§aLa configuración ha sido recargada con éxito."
