name: 'PrivateWarps'
main: 'pw.spannercraft.PrivateWarps'
version: '1.2.0'
api-version: '1.20'
commands:
  setpwarp:
    description: 'Crea un warp privado'
    usage: '/setpwarp <nombre>'
    permission: 'privatewarps.set'  # Esto vincula el comando al permiso correspondiente
  delpwarp:
    description: 'Elimina un warp privado'
    usage: '/delpwarp <nombre>'
    permission: 'privatewarps.del'  # Permiso para eliminar warps
  pwarp:
    description: 'Muestra la lista de warps o teletransporta al warp'
    usage: '/pwarp [nombre]'
    permission: 'privatewarps.pwarp'  # Permiso para ver y teletransportarse
  pwarpreload:
    description: 'Recarga la configuración del plugin'
    usage: '/pwarpreload'
    permission: 'privatewarps.reload'  # Permiso para recargar la configuración
permissions:
  privatewarps.set:
    description: 'Permite crear warps privados'
    default: true
  privatewarps.del:
    description: 'Permite eliminar warps privados'
    default: true
  privatewarps.reload:
    description: 'Permite recargar la configuración del plugin'
    default: 'op'
  privatewarps.pwarp:
    description: 'Permite ver la lista de warps y teletransportarse a ellos'
    default: true  # Si deseas permitir que todos los jugadores puedan usar el comando
