name: 'PrivateWarps'
main: 'pw.spannercraft.PrivateWarps'
version: '1.3.1'
api-version: '1.20'
description: "Un plugin para crear y gestionar warps privados por jugador."
author: "Spanneredu"
commands:
  setpwarp:
    description: "Crea un warp privado en tu ubicaci贸n actual."
    usage: "/setpwarp <nombre>"
    permission: 'privatewarps.setpwarp'
    permission-message: "No tienes permiso para usar este comando."

  delpwarp:
    description: "Elimina un warp privado."
    usage: "/delpwarp <nombre>"
    permission: 'privatewarps.delpwarp'
    permission-message: "No tienes permiso para usar este comando."

  pwarp:
    description: "Accede a tus warps privados."
    usage: "/pwarp <nombre>"
    permission: 'privatewarps.pwarp'
    permission-message: "No tienes permiso para usar este comando."

  pwarpreload:
    description: "Recarga la configuraci贸n del plugin."
    usage: "/pwarpreload"
    permission: 'privatewarps.reload'
    permission-message: "No tienes permiso para recargar la configuraci贸n."
permissions:
  privatewarps.setpwarp:
    description: "Permiso para crear un warp privado."
    default: 'op'
  privatewarps.delpwarp:
    description: "Permiso para eliminar un warp privado."
    default: 'op'
  privatewarps.pwarp:
    description: "Permiso para teletransportarse a warps privados."
    default: 'op'
  privatewarps.reload:
    description: "Permiso para recargar la configuraci贸n del plugin."
    default: 'op'
